config/routes.rb
QuacksRails::Application.routes.draw do
  root :to => "authors#index"

  resources :authors, only: [:index, :show, :create, :update, :new]
  resources :users, only: [:index, :show, :update]
  resources :images, only: [:edit, :update]

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :user_id

  def user_id
    session[:user_id]
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @view = AuthorsView.new
    presenter = AuthorsPresenter.new(@view, DB.new)
    presenter.update_view
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    author_id = params[:id].to_i
    @view = AuthorView.new
    presenter = AuthorPresenter.new(author_id, @view, DB.new)
    presenter.update_view
  end

  def new
  end

  # POST /authors
  # POST /authors.json
  def create
    name = params[:name]
    t = AddAuthor.new(params[:name], DB.new) if not name.blank?
    t.execute

    redirect_to author_path(t.author_id)
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    author_id = params[:id].to_i
    quote = params[:quote]
    if user_id and not quote.blank?
      t = AddQuote.new(user_id, author_id, quote, DB.new)
      t.execute
    end
    redirect_to author_path(author_id)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def edit
    @author_id = params[:id].to_i
  end

  def update
    redirect_to author_path(author_id) unless user_id

    author_id = params[:id].to_i
    url = params[:url]
    t = AddImage.new(author_id, url, DB.new)
    t.execute
    redirect_to author_path(author_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    au = AddUser.new(auth["info"]["name"], auth["info"]["nickname"], DB.new)
    au.execute
    session[:user_id] = au.user_id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user_id = params[:id].to_i
    @view = UserView.new
    presenter = UserPresenter.new(user_id, @view, DB.new)
    presenter.update_view
  end

  def index
    @view = UsersView.new
    presenter = UsersPresenter.new(@view, DB.new)
    presenter.update_view
  end

  def update
    type = params[:commit]
    quote_id = params[:quote_id].to_i
    if user_id and quote_id
      if type =~ /\+/
        t = UserLikesQuote.new(user_id, quote_id, DB.new)
      elsif type =~ /\-/
        t = UserDislikesQuote.new(user_id, quote_id, DB.new)
      end
    end
    t.execute
    redirect_to user_path(user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/index.html.erb
<table>
  <thead></thead>
  <tbody>
<% @view.authors.each do |author| %>
    <tr>
      <td>
        <div align="right">
        <figure>
          <a class="" href="<%= author_path(author[:id]) %>">
            <img src="<%= author[:img_src] %>"/>
          </a>
        </figure>
        </div>
      </td>
      <td>
        <h3><%= link_to author[:name], author_path(author[:id]) %></h3>
        <blockquote>
          <p>
            <%= author[:quote] %>
          </p>
        </blockquote>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
<br />
<%= link_to 'Add Author', new_author_path, :class => "btn" %>

app/views/authors/new.html.erb
<% if user_id %>
  <%= form_tag(authors_path, :method => "post", html: { class:
  "form-horizontal" }) do  %>
  <fieldset>
    <div class="control-group">
      <%= label_tag :author, "Name", :class => "control-label" %>
      <div class="controls">
        <%= text_field_tag(:name, "", :class => "text_field") %>
      </div>
      <div class="form-actions">
        <%= submit_tag("Add Author", :class => "btn btn-primary") %>
        <%= link_to "Go Back", authors_path, :class => "btn" %>
      </div>
    </div>
  </fieldset>
  <% end %>
<% else %>
  You need to be signed in
  <div class="form-actions">
    <%= link_to "Go Back", authors_path, :class => "btn" %>
  </div>
<% end %>

app/views/authors/show.html.erb
<table>
  <thead></thead>
  <tbody>
    <tr>
      <td>
    <a href="<%= edit_image_path(@view.author[:id]) %>" class="">
      <div class="">
        <figure>
          <% if @view.author[:img_src] %>
            <img src="<%= @view.author[:img_src] %>" />
          <% else %>
            <%= link_to "Add Image", edit_image_path(@view.author[:id]) %>
          <% end %>
        </figure>
      </div>
    </a>
    </td>
      <td>
      <div class="">
        <h3><%= @view.author[:name] %></h3>
      </div>
      </td>
    </tr>
  </tbody>
</table>
<div class="quotes">
  <table class="table table-striped">
  <thead><tr><td></td></tr></thead>
  <tbody>
  <% @view.quotes.each do |quote| %>
  <tr><td>

    <p><%= quote[:text] %></p>
    <% if user_id %>
    <%= form_tag(user_path(user_id), method: "put", class: "form-horizontal") do %>
      <div class="control-group">
        <%= hidden_field_tag("quote_id", quote[:id]) %>
        <%= submit_tag("+#{quote[:likes]}", class: "btn btn-primary") %>
        <%= submit_tag("-#{quote[:dislikes]}", class: "btn btn-danger") %>
      </div>
    <% end %>
    <% else %>
      <%= submit_tag("+#{quote[:likes]}", class: "btn btn-primary disabled") %>
      <%= submit_tag("-#{quote[:dislikes]}", class: "btn btn-danger disabled") %>
      <br />
      <br />
    <% end %>
    <small>Created by <cite><%= link_to quote[:user_name],
    user_path(quote[:user_id]) %></cite>
      </small>

  </td></tr>
  <% end %>
</tbody>
</table>
</div>
<% if user_id %>
  <div class="add_quote">
    <h2>Add Quote</h2>
    <%= form_tag(author_path(@view.author[:id]), :method => "put") do %>
      <%= text_area_tag(:quote) %>
      <%= submit_tag("Add Quote", class: "btn") %>
    <% end %>
  </div>
<% end %>
<%= link_to 'Back', authors_path %>

app/views/images/edit.html.erb
<% if user_id %>
  <%= form_tag(image_path(@author_id), method: "put") do %>
    <%= text_field_tag("url") %>
    <%= submit_tag("Add Image") %>
  <% end %>
<% else %>
  <h4>You need to be logged in to change images</h4>
  <%= link_to "Back", author_path(@author_id) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quacks</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse"
  data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="<%= authors_path %>">QUACKS</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Authors", authors_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <% if user_id %>
              <li><%= link_to "My Quotes", user_path(user_id) %></li>
              <li><%= link_to "Signout", signout_path %></li>
            <% else %>
              <li><%= link_to "Sign in with Twitter", "/auth/twitter"%></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div id="container" class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>
<% @view.users.each do |user| %>
<table>
  <thead></thead>
  <tbody>
    <td>
      <a href="<%= user_path(user[:id]) %>">
        <figure>
          <img src="" alt="gravatar_img" />
        </figure>
      </a>
    </td>
    <td>
    <h3><%= link_to user[:name], user_path(user[:id]) %> -- <%= user[:score] %></h3>
  <% if user[:quote] %>
  <blockquote>
  <p><%= user[:quote] %> -- <%= link_to user[:author], author_path(user[:author_id]) %></p>
  <% if user_id %>
  <%= form_tag(user_path(user_id), method: "put") do %>
    <%= hidden_field_tag("quote_id", user[:quote_id]) %>
    <%= submit_tag("+#{user[:likes]}", class: "btn btn-primary") %>
    <%= submit_tag("-#{user[:dislikes]}", class: "btn btn-danger") %>
  <% end %>
  <% else %>
    <%= submit_tag("+#{user[:likes]}", class: "btn btn-primary disabled") %>
    <%= submit_tag("-#{user[:dislikes]}", class: "btn btn-danger disabled") %>
  <% end %>
  <% end %>
  </blockquote>
  </td>
  </tbody>
</table>
<% end %>

app/views/users/show.html.erb
<h1><%= @view.user[:name] %></h1>

<h2>Quotes Added</h2>

<div class="quotes">
  <table class="table">
  <thead><tr><td></td><td></td></tr></thead>
  <tbody>
  <% @view.quotes.each do |quote| %>
  <tr>
    <td>
      <div align="right">
      <a href="<%= author_path(quote[:author_id]) %>" class="">
        <img src="<%= quote[:author_img_src] %>" />
      </a>
      </div>
    </td>
    <td>
      <p><%= quote[:text] %> --
      <small>
          <%= link_to quote[:author_name], author_path(quote[:author_id]) %>
      </small>
      </p>

      <% if user_id %>
      <%= form_tag(user_path(user_id), method: "put", class: "form-horizontal") do %>
        <div class="control-group">
          <%= hidden_field_tag("quote_id", quote[:id]) %>
          <%= submit_tag("+#{quote[:likes]}", class: "btn btn-primary") %>
          <%= submit_tag("-#{quote[:dislikes]}", class: "btn btn-danger") %>
        </div>
      <% end %>
      <% else %>
        <%= submit_tag("+#{quote[:likes]}", class: "btn btn-primary disabled") %>
        <%= submit_tag("-#{quote[:dislikes]}", class: "btn btn-danger disabled") %>
      <% end %>
    </td>
  </tr>
  <% end %>
</tbody>
</table>
</div>

<h2>Quotes Liked</h2>
<div class="quotes">
  <table class="table">
  <thead><tr><td></td><td></td></tr></thead>
  <tbody>
  <% @view.quotes.each do |quote| %>
  <tr>
    <td>
      <div align="right">
      <a href="<%= author_path(quote[:author_id]) %>" class="">
        <img src="<%= quote[:author_img_src] %>" />
      </a>
      </div>
    </td>
    <td>
      <p><%= quote[:text] %> --
      <small>
          <%= link_to quote[:author_name], author_path(quote[:author_id]) %>
      </small>
      </p>

      <% if user_id %>
      <%= form_tag(user_path(user_id), method: "put", class: "form-horizontal") do %>
        <div class="control-group">
          <%= hidden_field_tag("quote_id", quote[:id]) %>
          <%= submit_tag("+#{quote[:likes]}", class: "btn btn-primary") %>
          <%= submit_tag("-#{quote[:dislikes]}", class: "btn btn-danger") %>
        </div>
      <% end %>
      <% else %>
        <%= submit_tag("+#{quote[:likes]}", class: "btn btn-primary disabled") %>
        <%= submit_tag("-#{quote[:dislikes]}", class: "btn btn-danger disabled") %>
      <% end %>
    </td>
  </tr>
  <% end %>
</tbody>
</table>
</div>

<h2>Quotes Disliked</h2>
<div class="quotes">
  <table class="table">
  <thead><tr><td></td><td></td></tr></thead>
  <tbody>
  <% @view.quotes.each do |quote| %>
  <tr>
    <td>
      <div align="right">
      <a href="<%= author_path(quote[:author_id]) %>" class="">
        <img src="<%= quote[:author_img_src] %>" />
      </a>
      </div>
    </td>
    <td>
      <p><%= quote[:text] %> --
      <small>
          <%= link_to quote[:author_name], author_path(quote[:author_id]) %>
      </small>
      </p>

      <% if user_id %>
      <%= form_tag(user_path(user_id), method: "put", class: "form-horizontal") do %>
        <div class="control-group">
          <%= hidden_field_tag("quote_id", quote[:id]) %>
          <%= submit_tag("+#{quote[:likes]}", class: "btn btn-primary") %>
          <%= submit_tag("-#{quote[:dislikes]}", class: "btn btn-danger") %>
        </div>
      <% end %>
      <% else %>
        <%= submit_tag("+#{quote[:likes]}", class: "btn btn-primary disabled") %>
        <%= submit_tag("-#{quote[:dislikes]}", class: "btn btn-danger disabled") %>
      <% end %>
    </td>
  </tr>
  <% end %>
</tbody>
</table>
</div>